/**
 * Release binaries (Part 4 §10.5): the server compiled with Bun, the built app, the export viewer
 * and the author guide embedded, so one file serves the current folder with nothing installed.
 *
 *   bun run build && bun run build:release [--target macos-arm64,linux-x64]
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, relative, sep } from 'node:path'

const ROOT = join(import.meta.dir, '..')
const STUB = join(ROOT, 'server', 'embedded.generated.ts')
const STUB_TEXT = readFileSync(STUB, 'utf8')

export const TARGETS: Record<string, string> = {
  'macos-arm64': 'bun-darwin-arm64',
  'macos-x64': 'bun-darwin-x64',
  'linux-x64': 'bun-linux-x64',
  'linux-arm64': 'bun-linux-arm64',
  'windows-x64': 'bun-windows-x64',
}

function walk(dir: string): string[] {
  if (!existsSync(dir)) return []
  const out: string[] = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) out.push(...walk(full))
    else if (!entry.name.startsWith('.')) out.push(full)
  }
  return out
}

const rel = (file: string) => relative(ROOT, file).split(sep).join('/')

/** Every app file the server reads: public/, dist/ (minus copies of public/), the author guide. */
export function embeddedFiles(): string[] {
  const publicFiles = walk(join(ROOT, 'public'))
  const publicNames = new Set(publicFiles.map((f) => relative(join(ROOT, 'public'), f)))
  const distFiles = walk(join(ROOT, 'dist')).filter((f) => !publicNames.has(relative(join(ROOT, 'dist'), f)))
  return [...publicFiles, ...distFiles, join(ROOT, 'docs', 'agents', 'presentation-author.md')].map(rel).sort()
}

export function embeddedModule(files: string[]): string {
  const imports = files.map((f, i) => `import f${i} from '../${f}' with { type: 'file' }`)
  const entries = files.map((f, i) => `  ${JSON.stringify(f)}: f${i},`)
  return `// Generated by scripts/buildRelease.ts. Never commit this form; the tracked file is the empty map.\n${imports.join('\n')}\n\nexport const embedded: Record<string, string> = {\n${entries.join('\n')}\n}\n`
}

async function main() {
  for (const need of ['dist/index.html', 'dist/viewer/viewer.js', 'docs/agents/presentation-author.md']) {
    if (!existsSync(join(ROOT, need))) {
      console.error(`Missing ${need}. Run "bun run build" first.`)
      process.exit(1)
    }
  }
  const arg = process.argv.find((a) => a.startsWith('--target='))?.slice('--target='.length) ?? process.argv[process.argv.indexOf('--target') + 1]
  const wanted = process.argv.includes('--target') || arg ? (arg ?? '').split(',').filter(Boolean) : Object.keys(TARGETS)
  const unknown = wanted.filter((t) => !TARGETS[t])
  if (unknown.length) {
    console.error(`Unknown target(s): ${unknown.join(', ')}. Known: ${Object.keys(TARGETS).join(', ')}`)
    process.exit(1)
  }
  const version = (JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')) as { version: string }).version
  const files = embeddedFiles()
  mkdirSync(join(ROOT, 'release'), { recursive: true })
  console.log(`Embedding ${files.length} files; Slidecraft ${version}`)

  writeFileSync(STUB, embeddedModule(files))
  try {
    for (const name of wanted) {
      const outfile = join(ROOT, 'release', `slidecraft-${name}${name.startsWith('windows') ? '.exe' : ''}`)
      const proc = Bun.spawn(
        ['bun', 'build', '--compile', `--target=${TARGETS[name]}`, '--minify', '--external', 'sharp', `--define`, `process.env.SLIDECRAFT_VERSION=${JSON.stringify(version)}`, 'server/index.ts', '--outfile', outfile],
        { cwd: ROOT, stdout: 'inherit', stderr: 'inherit' },
      )
      if ((await proc.exited) !== 0) throw new Error(`bun build failed for ${name}`)
      console.log(`  ${rel(outfile)}`)
    }
  } finally {
    writeFileSync(STUB, STUB_TEXT) // the tracked file stays the empty map
  }
}

if (import.meta.main) await main()
