/**
 * Instructions for agents working in a content folder (Part 4 §7.6): a generated AGENTS.md built
 * from the component registry, the templates and the available themes, followed by the author
 * guide. A hand-written AGENTS.md is never touched.
 */
import { existsSync, readFileSync } from 'node:fs'
import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { getAllComponents, getAllTemplates } from '../../src/components/slides/defineComponent.ts'
import '../../src/components/slides/index.ts'
import { readAuthorGuide } from './appFiles.ts'
import { getDefaultContentSource } from './contentSources.ts'
import { VERSION } from './paths.ts'
import { executeTool } from './tools.ts'

export const GENERATED_PREFIX = '<!-- Generated by Slidecraft'
export const CONTENT_INSTRUCTIONS_FILE = 'AGENTS.md'

const CATEGORIES: Record<string, string[]> = {
  Structure: ['Presentation', 'Slide', 'Notes', 'Step'],
  Text: ['Title', 'Subtitle', 'Text', 'Accent', 'Highlight', 'Caption', 'Quote', 'CenteredStatement', 'TagPill', 'Section', 'Code'],
  Lists: ['List', 'ListItem', 'ProConList'],
  Layout: ['TwoColumn', 'FourColumn', 'Stack', 'Divider', 'SplitBackground', 'ComparisonLayout', 'DefinitionLayout', 'PersonRow'],
  Content: ['Card', 'Callout', 'ContentBox', 'PersonCard', 'Legend', 'IconRow', 'PhaseRow', 'ComparisonTable'],
  'Data Visualization': ['Stat', 'ProgressBar', 'Spectrum', 'Timeline', 'Quadrants', 'ScatterChart'],
  'Technical Diagrams': ['BlockDiagram', 'StackDiagram', 'CycleDiagram', 'PyramidDiagram', 'SequenceDiagram', 'ActivityDiagram', 'DataModel', 'FeedbackLoops', 'AppShellDiagram', 'BracketDiagram'],
  Media: ['ContentImage', 'Svg', 'BackgroundImage', 'YouTube'],
}

/** Component list grouped by category, with every component's props. */
export function buildComponentSummary(): string {
  const all = getAllComponents().map((c) => c.registry)
  const known = new Set(Object.values(CATEGORIES).flat())
  const groups = { ...CATEGORIES, Other: all.map((r) => r.name).filter((n) => !known.has(n)) }
  const lines = ['## Available components', '', '| Category | Components |', '|---|---|']
  for (const [category, names] of Object.entries(groups)) if (names.length) lines.push(`| ${category} | ${names.join(', ')} |`)
  lines.push('', '### Props', '')
  for (const r of all) {
    const props = r.props.map((p) => `\`${p.name}\`${p.default ? ` = ${p.default}` : ''}`).join(', ')
    lines.push(`- **${r.name}** — ${r.description}${props ? ` Props: ${props}.` : ''}`)
  }
  return lines.join('\n')
}

export function buildTemplateExamples(): string {
  const lines = ['## Slide templates', '', 'Starting points for whole slides:', '']
  for (const t of getAllTemplates()) lines.push(`### ${t.name}`, '', t.description, '', '```mdx', t.snippet, '```', '')
  return lines.join('\n')
}

export async function buildThemeSummary(): Promise<string> {
  const result = await executeTool('list_themes', {})
  const { themes, errors } = result.data as { themes: { id: string; name: string; description?: string; frames: string[]; source: string }[]; errors: Record<string, string[]> }
  const lines = ['## Themes', '', 'Set one on the deck root: `<Presentation theme="…">`.', '', '| Theme | From | Frames | Description |', '|---|---|---|---|']
  for (const t of themes) lines.push(`| \`${t.id}\` | ${t.source === 'builtin' ? 'built-in' : 'this folder'} | ${t.frames.length ? t.frames.map((f) => `\`${f}\``).join(', ') : '—'} | ${t.description ?? ''} |`)
  for (const [id, problems] of Object.entries(errors)) lines.push('', `Theme \`${id}\` has problems: ${problems.join('; ')}`)
  return lines.join('\n')
}

export async function buildFolderInstructions(port: number): Promise<string> {
  const guide = readAuthorGuide()
  return [
    `${GENERATED_PREFIX} ${VERSION}. Slidecraft rewrites this file on start when it is out of date; do not edit it. -->`,
    '# Presentations in this folder',
    '',
    'Each subfolder holding an `index.mdx` is one presentation; the folder name is its URL. Images go next to the file and are imported by relative path. Themes live in `themes/<id>/theme.json`.',
    '',
    `- **Create** a presentation: write \`<name>/index.mdx\` (lower-case words joined by dashes) and tell the user to open http://localhost:${port}/<name>.`,
    '- **Change** one: edit its `index.mdx` in place; the open presentation reloads on save.',
    '- Import components from `@components` only. Never use raw HTML.',
    '',
    buildComponentSummary(),
    '',
    buildTemplateExamples(),
    await buildThemeSummary(),
    '',
    '# Authoring guide',
    '',
    guide ?? 'See the Slidecraft documentation for the authoring rules.',
    '',
  ].join('\n')
}

export const isGenerated = (text: string): boolean => text.startsWith(GENERATED_PREFIX)

/** Folder instructions written by a person (never the generated file). */
export function readContentInstructions(dir = getDefaultContentSource().path): string | null {
  const file = join(dir, CONTENT_INSTRUCTIONS_FILE)
  if (!existsSync(file)) return null
  const text = readFileSync(file, 'utf8')
  return isGenerated(text) ? null : text
}

export type SyncResult = 'written' | 'unchanged' | 'hand-written' | 'read-only' | 'missing-dir'

/** Generate or refresh AGENTS.md in the default content folder. */
export async function syncFolderInstructions(port: number): Promise<SyncResult> {
  const source = getDefaultContentSource()
  if (source.readOnly) return 'read-only'
  if (!existsSync(source.path)) return 'missing-dir'
  const file = join(source.path, CONTENT_INSTRUCTIONS_FILE)
  const existing = existsSync(file) ? readFileSync(file, 'utf8') : null
  if (existing !== null && !isGenerated(existing)) return 'hand-written'
  const wanted = await buildFolderInstructions(port)
  if (existing === wanted) return 'unchanged'
  try {
    await writeFile(file, wanted)
    return 'written'
  } catch (error) {
    console.warn(`Could not write ${file}: ${(error as Error).message}`)
    return 'unchanged'
  }
}
